---
task_kwargs:
  use_pixels: True
  use_segment: True
  sample_target: True
  target_from_sites: False
  dense_reward: True
  random_init_distance: 0.001

wrapper_kwargs:
  use_obs:
    - 'pixels'
    - 'guidewire'
    - 'joint_pos'
    - 'joint_vel'

algo_kwargs:
  replay_buffer_class: 'HerReplayBuffer'
