[build-system]
requires = ["setuptools", "wheel==0.38.4"]
build-backend = "setuptools.build_meta"

[project]
name = "cathsim"
version = "0.1.dev1"
description = "Endovascular simulator for autonomy development"
readme = "README.md"  # Point this to your README file if you have one.
# Homepage = "https://robotvisionlabs.github.io/cathsim/"
# Documentation = "https://readthedocs.org"
# Repository = "https://github.com/robotvisionlabs/cathsim"
license = { file = "LICENSE" }
authors = [
    {name = "Tudor Jianu", email = "tudorjnu@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Free for non-commercial use",
    "Operating System :: OS Independent",
]
dependencies = [
  "gym==0.21.*",
  "dm-control",
  "pyyaml",
  "opencv-python",
  "matplotlib",
  "stable-baselines3==1.8.0",
  "torch",
  "imitation",
  "tqdm",
  "rich",
  "mergedeep",
  "progressbar2",
  "progress",
  "trimesh",
  "rtree",
  "toolz"
]




[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
    "sphinxcontrib.spelling",
    "sphinx-autodoc-typehints",
    "sphinx_copybutton"
]
dev = ["pytest"]

[project.scripts]
run_env = "utils.console:cmd_run_env"
visualize_agent = "utils.console:cmd_visualize_agent"
train = "utils.console:cmd_train"
