---
task_kwargs:
  use_pixels: True
  use_segment: True
  random_init_distance: 0.001
  sample_target: True
  target_from_sites: False
  

wrapper_kwargs:
  use_obs:
    - 'pixels'
    - 'guidewire'
    - 'joint_pos'
    - 'joint_vel'





